### ISSUE TITLE
Modelling tonic and phasic components

### ISSUE THREAD

**Issue by samhforbes** [ihrke/pypillometry#1]
Hi @ihrke,
I've been having some fun playing around with the options you have here.
In the paper you claim a strength of this package is modelling tonic and phasic components of the signal, but (for me at least), the notebook section for that (modelling data) just comes up with TO DO:

I feel like there's scope for some things to be a work in progress, but it might be helpful for complete documentation to be able to see some of these options, but also to be able to test those functions work the way they should

**Comment by ihrke** [comment]
That's a fair point. In fact, I am currently writing a methodological paper on a new baseline and response-estimation technique and this technique is already implemented in the package (but not very well documented). I kind of wanted to wait until the paper is finished before officially promoting these functions in the package. But I can see the point that a package user would want to get some kind of idea what this module is about. 

Would you be ok if I added some documentation to the pupil-modelling section in the docs while adding a warning that this is an experimental and yet untested part of the package?

**Comment by samhforbes** [comment]
Yeah I can fully understand wanting to wait. But I do think especially as this is functionality which is unique to your package (and therefore super cool!), it would really strengthen it, even if only experimental features or a basic example with detailed analyses to come.

**Comment by ihrke** [comment]
sorry, that commit (77f3795) is not related to this issue but to #3. I fixed the commit message but it still shows up here...

**Comment by ihrke** [comment]
Hi @samhforbes,

I added some documentation to the modeling-section in the docs and also added a notebook explaining all the details of the experimental baseline- and response-estimation methods. 
Let me know if you are happy with this!

**Comment by samhforbes** [comment]
I'm satisfied with these changes, it looks interesting and I can get these notebooks to work.
This is in great shape. I'm happy for you to close this, but I'll leave it to you because I don't know whether there are any further thoughts from https://github.com/openjournals/joss-reviews/issues/2348#issuecomment-650473510

Great work!

**Comment by ihrke** [comment]
thanks @samhforbes! I'll close this now and we can see whether it needs reopening...

**Comment by szorowi1** [comment]
Just wanted to follow up to say that I've had another look through the modeling docs and I'm satisfied!
