### ISSUE TITLE
Blink detection on Pupil Labs data

### ISSUE THREAD

**Issue by jtmbeta** [ihrke/pypillometry#11]
I am attempting to detect blinks in Pupil Labs pupillometry data but I get the following error when using .blinks_detect():

`IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1`

I am attaching the script and example data. Are you able to replicate the issue?

Best,
joel

[issue.zip](https://github.com/ihrke/pypillometry/files/5881403/issue.zip)

**Comment by wsojka00** [comment]
Hey, how did you manage to overcome this error?

**Comment by jtmbeta** [comment]
Hey, I couldn't get the software to work with Pupil Labs data in the end. Pupil labs data have uneven timestamps, which you can see for yourself by plotting np.diff(timestamp). I suspected this was causing the issue and wrote my own code. If you are working with Pupil Labs, you might find it useful: https://github.com/PyPlr/cvd_pupillometry

**Comment by wsojka00** [comment]
Thank you very much for your response, we're not working with Pupil Labs, but I'll take a look.
