### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by samhforbes** [ihrke/pypillometry#2]
@ihrke I can't currently see a clear community guidelines statement on the documentation website or in the README. Remember some of your users may not be familiar with github etiquette, so if you can state on either or both how to contact you, how to report bugs etc, that would be welcome.

**Comment by ihrke** [comment]
good points! Can you check whether this commit (dd9974e) addresses this issue sufficiently @samhforbes?
In addition to your requests, I have also added some more information for potential contributors about how the package was designed.

**Comment by samhforbes** [comment]
This is great, thanks!
