### ISSUE TITLE
References for JOSS paper

### ISSUE THREAD

**Issue by samhforbes** [ihrke/pypillometry#3]
@ihrke The paper looks good, but there are a few references missing DOIs (Joshi et al., Kluyver et al., Laeng et al., and Mittner et al.).
I'd also be grateful if you wouldn't mind updating the PupillometryR reference to the JOSS paper (Forbes, S. H. (2020). PupillometryR: An R package for preparing and analysing pupillometry data. Journal of Open Source Software, 5(50), 2285. https://doi.org/10.21105/joss.02285)

**Comment by ihrke** [comment]
thanks for spotting those and congrats on the published JOSS paper!
I don't know what the etiquette for the review process is - should I leave it up to you to close the issue, @samhforbes?

**Comment by samhforbes** [comment]
I think you can close issues if you're satisfied, we can always re-open if necessary ;)
This looks good!
