### ISSUE TITLE
Installation instructions for PyStan

### ISSUE THREAD

**Issue by samhforbes** [ihrke/pypillometry#4]
Hi @ihrke,
This is more of a suggestion for you to look at, but getting PyStan going can be an issue for users especially if they move outside of jupyter. Given they have a fair amount of documentation on these issues, perhaps it's worth linking users across or highlighting some of the main troubleshooting tips (needing compilers in windows for example).

**Comment by ihrke** [comment]
Hei @samhforbes, 
can you check whether you are happy with the changes I made to the installation instructions? See f7d986a.

**Comment by samhforbes** [comment]
@ihrke that's a neat addition - very happy.
