### ISSUE TITLE
Additional installation instructions

### ISSUE THREAD

**Issue by szorowi1** [ihrke/pypillometry#5]
Hi @ihrke! First off, this package is great! As a small suggestion, I might consider adding additional installation instructions in the README. For example, folks can install pypillometry directly from Github using:

```bash
pip install git+https://github.com/ihrke/pypillometry.git
```

I was also wondering if you were planning on uploading pypillometry to pypi? This might help make this awesome package more discoverable by python users.

**Comment by ihrke** [comment]
Hi @szorowi1,

very good point, thanks! I have uploaded `pypillometry` to PyPI and it should be possible to install it (and all dependencies using just `pip install pypillometry`).

**Comment by szorowi1** [comment]
Hi again

On the installation page (https://ihrke.github.io/pypillometry/html/docs/installation.html), I'm not sure if there is supposed to be a line of code following _"pypillometry is on PyPI and released versions can be installed with pip:"_ with the install command. Otherwise, I think it looks great and congrats on the pypi release!

**Comment by ihrke** [comment]
you are right, I messed up some indentation in the `.rst` source-file. I fixed it in 2b4a9b081d2a50f45adb790b1cc58c14020fdc6e

**Comment by szorowi1** [comment]
Thanks for the fix. It looks great! Feel free to close the issue if you're happy with it!
